spring:
  application:
    name: oidc-reference-backend
  profiles:
    default: dev

server:
  port: 8180
  forward-headers-strategy: none
  servlet:
    session:
      timeout: 30m
      tracking-modes: cookie
      persistent: false
      cookie:
        name: RP_SESSION
        path: /
        http-only: true
        same-site: lax
        secure: true
